// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using alugueis_api.Data;

#nullable disable

namespace Alugueis_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("alugueis_api.Models.Apto", b =>
                {
                    b.Property<int>("CodApto")
                        .HasColumnType("int");

                    b.Property<int>("Andar")
                        .HasColumnType("int");

                    b.Property<int>("CodPredio")
                        .HasColumnType("int");

                    b.Property<int>("MetrosQuadrados")
                        .HasColumnType("int");

                    b.Property<int>("QtdBanheiros")
                        .HasColumnType("int");

                    b.Property<int>("QtdQuartos")
                        .HasColumnType("int");

                    b.HasKey("CodApto");

                    b.HasIndex("CodPredio");

                    b.ToTable("Aptos");
                });

            modelBuilder.Entity("alugueis_api.Models.Despesa", b =>
                {
                    b.Property<int>("CodDespesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodDespesa"));

                    b.Property<int>("CodTipoDespesa")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("datetime2");

                    b.Property<float>("VrlTotalDespesa")
                        .HasColumnType("real");

                    b.HasKey("CodDespesa");

                    b.HasIndex("CodTipoDespesa");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("alugueis_api.Models.DespesaRateio", b =>
                {
                    b.Property<int>("CodDespesa")
                        .HasColumnType("int");

                    b.Property<int>("CodApto")
                        .HasColumnType("int");

                    b.Property<float>("VlrRateio")
                        .HasColumnType("real");

                    b.HasKey("CodDespesa", "CodApto");

                    b.HasIndex("CodApto");

                    b.ToTable("DespesaRateios");
                });

            modelBuilder.Entity("alugueis_api.Models.Locacao", b =>
                {
                    b.Property<int>("CodLocacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodLocacao"));

                    b.Property<int>("CodApto")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataIncio")
                        .HasColumnType("datetime2");

                    b.Property<float>("VlrAluguel")
                        .HasColumnType("real");

                    b.Property<float>("VlrCausao")
                        .HasColumnType("real");

                    b.HasKey("CodLocacao");

                    b.HasIndex("CodApto");

                    b.HasIndex("Cpf");

                    b.ToTable("Locacoes");
                });

            modelBuilder.Entity("alugueis_api.Models.Locatario", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EnderecoUltimoImovel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("NomeLocatario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdDependentes")
                        .HasColumnType("int");

                    b.Property<int>("TemPet")
                        .HasColumnType("int");

                    b.HasKey("Cpf");

                    b.ToTable("Locatarios");
                });

            modelBuilder.Entity("alugueis_api.Models.Predio", b =>
                {
                    b.Property<int>("CodPredio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPredio"));

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePredio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdAndares")
                        .HasColumnType("int");

                    b.HasKey("CodPredio");

                    b.ToTable("Predios");
                });

            modelBuilder.Entity("alugueis_api.Models.TipoDespesa", b =>
                {
                    b.Property<int>("CodTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTipo"));

                    b.Property<int>("Compartilhado")
                        .HasColumnType("int");

                    b.Property<string>("NomeTipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodTipo");

                    b.ToTable("TiposDespesa");
                });

            modelBuilder.Entity("alugueis_api.Models.Apto", b =>
                {
                    b.HasOne("alugueis_api.Models.Predio", "Predio")
                        .WithMany("Aptos")
                        .HasForeignKey("CodPredio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("alugueis_api.Models.Despesa", b =>
                {
                    b.HasOne("alugueis_api.Models.TipoDespesa", "TipoDespesa")
                        .WithMany("Despesas")
                        .HasForeignKey("CodTipoDespesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDespesa");
                });

            modelBuilder.Entity("alugueis_api.Models.DespesaRateio", b =>
                {
                    b.HasOne("alugueis_api.Models.Apto", "Apto")
                        .WithMany("DespesasRateio")
                        .HasForeignKey("CodApto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alugueis_api.Models.Despesa", "Despesa")
                        .WithMany("Rateios")
                        .HasForeignKey("CodDespesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apto");

                    b.Navigation("Despesa");
                });

            modelBuilder.Entity("alugueis_api.Models.Locacao", b =>
                {
                    b.HasOne("alugueis_api.Models.Apto", "Apto")
                        .WithMany("Locacoes")
                        .HasForeignKey("CodApto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alugueis_api.Models.Locatario", "Locatario")
                        .WithMany("Locacoes")
                        .HasForeignKey("Cpf");

                    b.Navigation("Apto");

                    b.Navigation("Locatario");
                });

            modelBuilder.Entity("alugueis_api.Models.Apto", b =>
                {
                    b.Navigation("DespesasRateio");

                    b.Navigation("Locacoes");
                });

            modelBuilder.Entity("alugueis_api.Models.Despesa", b =>
                {
                    b.Navigation("Rateios");
                });

            modelBuilder.Entity("alugueis_api.Models.Locatario", b =>
                {
                    b.Navigation("Locacoes");
                });

            modelBuilder.Entity("alugueis_api.Models.Predio", b =>
                {
                    b.Navigation("Aptos");
                });

            modelBuilder.Entity("alugueis_api.Models.TipoDespesa", b =>
                {
                    b.Navigation("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
